### ISSUE TITLE
Command `start` crashes with segmentation fault

### ISSUE THREAD

**Issue by kernc** [elexis-eu/dictionary-service#2]
After installing from source, `elexis-dictionary-service start` segfaults:
```
$ RUST_BACKTRACE=1 target/release/elexis-dictionary-service start

Starting server at 0.0.0.0:8000
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<internal::SealedBag>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: std::sync::once::Once::call_once::{{closure}}
   4: std::sync::once::Once::call_inner
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sync/once.rs:419
   5: std::thread::local::fast::Key<T>::try_initialize
   6: crossbeam_epoch::default::pin
   7: tokio_threadpool::worker::entry::WorkerEntry::new
   8: tokio_threadpool::builder::Builder::build
   9: tokio::runtime::threadpool::builder::Builder::build
  10: gotham::new_runtime
  11: gotham::plain::start
  12: elexis_dictionary_service::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    2722 segmentation fault
```
```
$ RUST_BACKTRACE=full target/release/elexis-dictionary-service start

Starting server at 0.0.0.0:8000
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<internal::SealedBag>` uninitialized, which is invalid', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/mem/mod.rs:658:9
stack backtrace:
   0:     0x562d5a2d2e50 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x562d5a2d2e50 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x562d5a2d2e50 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x562d5a2d2e50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x562d5a2f33ec - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x562d5a2ccf62 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x562d5a2d523d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x562d5a2d523d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x562d5a2d523d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x562d5a2d4ee8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x562d5a2d5921 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x562d5a2d54c9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x562d5a2d32bc - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x562d5a2d5489 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x562d5a2f1cc1 - core::panicking::panic_fmt::h48c31e1e3d550146
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
  15:     0x562d5a2f1c0d - core::panicking::panic::h184ede6dd822ffb4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
  16:     0x562d5a26ee62 - std::sync::once::Once::call_once::{{closure}}::h2e292b7b84878f55
  17:     0x562d5a2d26f2 - std::sync::once::Once::call_inner::h2da0f98bb6169f9c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sync/once.rs:419
  18:     0x562d5a26ed27 - std::thread::local::fast::Key<T>::try_initialize::h876c93a9e01a69c8
  19:     0x562d5a255d9b - crossbeam_epoch::default::pin::h3666e643f14addc5
  20:     0x562d5a256d9f - tokio_threadpool::worker::entry::WorkerEntry::new::hd34bdc157cc2ce62
  21:     0x562d5a25a890 - tokio_threadpool::builder::Builder::build::h5c231af862ee825b
  22:     0x562d5a23cfef - tokio::runtime::threadpool::builder::Builder::build::h99d8dd84a20b956c
  23:     0x562d5a1a59b9 - gotham::new_runtime::h76043c983c78214b
  24:     0x562d5a0a9b83 - gotham::plain::start::h320ea1d6e07cbfc1
  25:     0x562d5a12b199 - elexis_dictionary_service::main::hff166fcbc1eb43d9
  26:     0x562d5a119c23 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcdc70b54391eb65c
  27:     0x562d5a065b49 - std::rt::lang_start::{{closure}}::h50f1144b90414ea5
  28:     0x562d5a2d5d47 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::he179d32a5d10d957
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:259
  29:     0x562d5a2d5d47 - std::panicking::try::do_call::hcb3d5e7be089b2b4
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:381
  30:     0x562d5a2d5d47 - std::panicking::try::h7ac93b0cd56fb701
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:345
  31:     0x562d5a2d5d47 - std::panic::catch_unwind::h7b40e396c93a4fcd
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panic.rs:382
  32:     0x562d5a2d5d47 - std::rt::lang_start_internal::h142b9cc66267fea1
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/rt.rs:51
  33:     0x562d5a12e4a2 - main
  34:     0x7fe93337609b - __libc_start_main
  35:     0x562d5a02a19a - _start
  36:                0x0 - <unknown>
[1]    3053 segmentation fault
```
```
$ rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```
Loading the examples seemingly worked.

After `cargo update`, the source no longer builds. :sweat_smile:

**Comment by jmccrae** [comment]
I can't reproduce this, the error appears to be with the `gotham` crate that this project is built on.
I updated the versions in `Cargo.toml` so perhaps this will solve the issue. Otherwise, could you provide the stacktrace when built with the `debug` settings

**Comment by kernc** [comment]
Above was already built without a `--release` switch.
```
$ git pull
...
$ cargo clean
$ cargo build
    Updating crates.io index
   Compiling libc v0.2.80
   Compiling cfg-if v0.1.10
   Compiling autocfg v0.1.2
   Compiling serde v1.0.88
   Compiling lazy_static v1.2.0
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling log v0.4.11
   Compiling syn v1.0.50
   Compiling semver-parser v0.7.0
   Compiling rand_core v0.4.0
   Compiling version_check v0.9.2
   Compiling cc v1.0.65
   Compiling slab v0.4.2
   Compiling itoa v0.4.3
   Compiling memchr v2.2.0
   Compiling proc-macro-hack v0.5.19
   Compiling once_cell v1.5.2
   Compiling proc-macro2 v0.4.27
   Compiling byteorder v1.3.1
   Compiling futures v0.1.25
   Compiling void v1.0.2
   Compiling unicode-xid v0.1.0
   Compiling fnv v1.0.6
   Compiling futures-core v0.3.8
   Compiling scopeguard v0.3.3
   Compiling ryu v0.2.7
   Compiling stable_deref_trait v1.1.1
   Compiling bytes v0.5.6
   Compiling arrayvec v0.4.10
   Compiling futures-sink v0.3.8
   Compiling proc-macro-nested v0.1.6
   Compiling rustc-demangle v0.1.13
   Compiling bitflags v1.0.4
   Compiling pin-project-lite v0.1.11
   Compiling nodrop v0.1.13
   Compiling pin-project-internal v0.4.27
   Compiling pulldown-cmark v0.2.0
   Compiling getrandom v0.1.15
   Compiling remove_dir_all v0.5.1
   Compiling pin-utils v0.1.0
   Compiling memoffset v0.2.1
   Compiling spin v0.5.2
   Compiling same-file v1.0.4
   Compiling untrusted v0.7.1
   Compiling futures-io v0.3.8
   Compiling httparse v1.3.3
   Compiling try-lock v0.2.2
   Compiling glob v0.2.11
   Compiling bytecount v0.4.0
   Compiling indexmap v1.0.2
   Compiling num-traits v0.2.6
   Compiling const_fn v0.4.3
   Compiling ppv-lite86 v0.2.10
   Compiling pkg-config v0.3.15
   Compiling num-integer v0.1.39
   Compiling regex v1.1.0
   Compiling cfg-if v1.0.0
   Compiling unicode-xid v0.0.4
   Compiling base64 v0.12.3
   Compiling linked-hash-map v0.5.1
   Compiling ucd-util v0.1.3
   Compiling anyhow v1.0.34
   Compiling quote v0.3.15
   Compiling tower-service v0.3.0
   Compiling mime v0.3.16
   Compiling unicode-width v0.1.5
   Compiling string v0.1.3
   Compiling either v1.6.1
   Compiling utf8-ranges v1.0.2
   Compiling httpdate v0.3.2
   Compiling strsim v0.7.0
   Compiling fallible-iterator v0.2.0
   Compiling fallible-streaming-iterator v0.1.9
   Compiling ansi_term v0.11.0
   Compiling percent-encoding v2.1.0
   Compiling vec_map v0.8.1
   Compiling pest v1.0.6
   Compiling quick-error v1.2.3
   Compiling xml-rs v0.8.3
   Compiling crossbeam-utils v0.6.5
   Compiling tracing-core v0.1.17
   Compiling thread_local v0.3.6
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.3
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling backtrace v0.3.13
   Compiling bincode v1.1.2
   Compiling futures-task v0.3.8
   Compiling unreachable v1.0.0
   Compiling standback v0.2.13
   Compiling unicase v2.6.0
   Compiling time v0.2.23
   Compiling cookie v0.14.3
   Compiling owning_ref v0.4.0
   Compiling futures-channel v0.3.8
   Compiling http v0.2.1
   Compiling walkdir v2.2.7
   Compiling synom v0.11.3
   Compiling backtrace-sys v0.1.28
   Compiling ring v0.16.16
   Compiling regex-syntax v0.6.5
   Compiling lru-cache v0.1.2
   Compiling textwrap v0.10.0
   Compiling itertools v0.9.0
   Compiling libsqlite3-sys v0.16.0
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling tokio-executor v0.1.6
   Compiling smallvec v0.6.8
   Compiling lock_api v0.1.5
   Compiling syn v0.11.11
   Compiling tracing v0.1.21
   Compiling want v0.3.0
   Compiling want v0.0.6
   Compiling tokio-timer v0.2.10
   Compiling tokio-current-thread v0.1.4
   Compiling quote v1.0.7
   Compiling crossbeam-channel v0.3.8
   Compiling iovec v0.1.4
   Compiling num_cpus v1.10.0
   Compiling net2 v0.2.33
   Compiling rand_os v0.1.2
   Compiling rand v0.4.6
   Compiling signal-hook-registry v1.2.2
   Compiling time v0.1.42
   Compiling socket2 v0.3.17
   Compiling atty v0.2.11
   Compiling mio v0.7.6
   Compiling aho-corasick v0.6.10
   Compiling http-body v0.3.1
   Compiling quote v0.6.11
   Compiling crossbeam-epoch v0.7.1
   Compiling bytes v0.4.11
   Compiling mime_guess v2.0.3
   Compiling futures-cpupool v0.1.8
   Compiling mio v0.6.21
   Compiling rand_core v0.5.1
   Compiling clap v2.32.0
   Compiling tempdir v0.3.7
   Compiling semver v0.9.0
   Compiling serde_json v1.0.38
   Compiling syn v0.15.26
   Compiling pest_derive v1.0.8
   Compiling crossbeam-deque v0.6.3
   Compiling rusqlite v0.20.0
   Compiling chrono v0.4.6
   Compiling tokio-io v0.1.11
   Compiling http v0.1.15
   Compiling rand_chacha v0.2.2
   Compiling rustc_version v0.2.3
   Compiling mio-uds v0.6.7
   Compiling sct v0.6.0
   Compiling webpki v0.21.3
   Compiling error-chain v0.12.0
   Compiling rand v0.7.3
   Compiling rand_pcg v0.1.1
   Compiling parking_lot_core v0.4.0
   Compiling rustls v0.18.1
   Compiling h2 v0.1.16
   Compiling serde_derive v1.0.88
   Compiling gotham_derive v0.3.0
   Compiling uuid v0.8.1
   Compiling pin-project-internal v1.0.2
   Compiling futures-macro v0.3.8
   Compiling tokio-macros v0.2.6
   Compiling time-macros-impl v0.1.1
   Compiling parking_lot v0.7.1
   Compiling tokio v0.2.22
   Compiling crossbeam v0.6.0
   Compiling tokio-reactor v0.1.8
   Compiling tokio-threadpool v0.1.11
   Compiling pin-project v1.0.2
   Compiling tokio-tcp v0.1.3
   Compiling time-macros v0.1.1
   Compiling futures-util v0.3.8
   Compiling pin-project v0.4.27
   Compiling tokio v0.1.15
   Compiling tracing-futures v0.2.4
   Compiling hyper v0.12.24
   Compiling cargo_metadata v0.6.4
   Compiling skeptic v0.13.4
   Compiling borrow-bag v1.0.0
   Compiling tokio-util v0.3.1
   Compiling tokio-rustls v0.14.1
   Compiling h2 v0.2.7
   Compiling futures-executor v0.3.8
   Compiling futures v0.3.8
   Compiling hyper v0.13.9
   Compiling gotham v0.5.0
   Compiling elexis-dictionary-service v0.1.0 (/tmp/dictionary-service)
error[E0277]: the trait bound `hyper::Body: HttpBody` is not satisfied
  --> src/main.rs:84:34
   |
84 | #[derive(Deserialize, StateData, StaticResponseExtender)]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpBody` is not implemented for `hyper::Body`
   | 
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gotham-0.5.0/src/router/response/extender.rs:11:19
   |
11 |     type ResBody: HttpBody;
   |                   -------- required by this bound in `StaticResponseExtender`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `hyper::Body: HttpBody` is not satisfied
  --> src/main.rs:88:34
   |
88 | #[derive(Deserialize, StateData, StaticResponseExtender)]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpBody` is not implemented for `hyper::Body`
   | 
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gotham-0.5.0/src/router/response/extender.rs:11:19
   |
11 |     type ResBody: HttpBody;
   |                   -------- required by this bound in `StaticResponseExtender`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `hyper::Body: HttpBody` is not satisfied
  --> src/main.rs:92:34
   |
92 | #[derive(Deserialize, StateData, StaticResponseExtender)]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpBody` is not implemented for `hyper::Body`
   | 
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gotham-0.5.0/src/router/response/extender.rs:11:19
   |
11 |     type ResBody: HttpBody;
   |                   -------- required by this bound in `StaticResponseExtender`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `hyper::Body: HttpBody` is not satisfied
  --> src/main.rs:97:34
   |
97 | #[derive(Deserialize, StateData, StaticResponseExtender)]
   |                                  ^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpBody` is not implemented for `hyper::Body`
   | 
  ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gotham-0.5.0/src/router/response/extender.rs:11:19
   |
11 |     type ResBody: HttpBody;
   |                   -------- required by this bound in `StaticResponseExtender`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `hyper::Body: HttpBody` is not satisfied
   --> src/main.rs:102:34
    |
102 | #[derive(Deserialize, StateData, StaticResponseExtender)]
    |                                  ^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpBody` is not implemented for `hyper::Body`
    | 
   ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gotham-0.5.0/src/router/response/extender.rs:11:19
    |
11  |     type ResBody: HttpBody;
    |                   -------- required by this bound in `StaticResponseExtender`
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `hyper::Body: HttpBody` is not satisfied
   --> src/main.rs:110:34
    |
110 | #[derive(Deserialize, StateData, StaticResponseExtender)]
    |                                  ^^^^^^^^^^^^^^^^^^^^^^ the trait `HttpBody` is not implemented for `hyper::Body`
    | 
   ::: ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gotham-0.5.0/src/router/response/extender.rs:11:19
    |
11  |     type ResBody: HttpBody;
    |                   -------- required by this bound in `StaticResponseExtender`
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 6 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `elexis-dictionary-service`
```
I'm not quite sure what all this is about.

**Comment by jmccrae** [comment]
Not sure either. I don't seem to get this error

```
-> % cargo build --release
   Compiling libc v0.2.80
   Compiling proc-macro2 v1.0.24
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.50
   Compiling version_check v0.9.2
   Compiling cfg-if v0.1.10
   Compiling getrandom v0.1.15
   Compiling log v0.4.11
   Compiling memchr v2.3.4
   Compiling serde v1.0.117
   Compiling autocfg v1.0.1
   Compiling proc-macro-hack v0.5.19
   Compiling ryu v1.0.5
   Compiling once_cell v1.5.2
   Compiling bitflags v1.2.1
   Compiling lazy_static v1.4.0
   Compiling slab v0.4.2
   Compiling serde_json v1.0.59
   Compiling rand_core v0.4.2
   Compiling futures-core v0.3.8
   Compiling autocfg v0.1.7
   Compiling proc-macro-nested v0.1.6
   Compiling futures-sink v0.3.8
   Compiling ppv-lite86 v0.2.10
   Compiling bytes v0.5.6
   Compiling pin-project-lite v0.1.11
   Compiling serde_derive v1.0.117
   Compiling fnv v1.0.7
   Compiling cc v1.0.65
   Compiling pulldown-cmark v0.2.0
   Compiling itoa v0.4.6
   Compiling semver-parser v0.7.0
   Compiling ahash v0.4.6
   Compiling pin-project-internal v0.4.27
   Compiling untrusted v0.7.1
   Compiling remove_dir_all v0.5.3
   Compiling spin v0.5.2
   Compiling same-file v1.0.6
   Compiling futures-io v0.3.8
   Compiling pin-utils v0.1.0
   Compiling glob v0.3.0
   Compiling bytecount v0.6.1
   Compiling const_fn v0.4.3
   Compiling httparse v1.3.4
   Compiling pkg-config v0.3.19
   Compiling byteorder v1.3.4
   Compiling try-lock v0.2.3
   Compiling cfg-if v1.0.0
   Compiling anyhow v1.0.34
   Compiling base64 v0.12.3
   Compiling unicode-xid v0.0.4
   Compiling unicode-width v0.1.8
   Compiling httpdate v0.3.2
   Compiling mime v0.3.16
   Compiling quote v0.3.15
   Compiling regex-syntax v0.6.21
   Compiling tower-service v0.3.0
   Compiling either v1.6.1
   Compiling fallible-streaming-iterator v0.1.9
   Compiling pest v1.0.6
   Compiling linked-hash-map v0.5.3
   Compiling fallible-iterator v0.2.0
   Compiling ansi_term v0.11.0
   Compiling smallvec v1.5.0
   Compiling vec_map v0.8.2
   Compiling percent-encoding v2.1.0
   Compiling strsim v0.8.0
   Compiling quick-error v1.2.3
   Compiling xml-rs v0.8.3
   Compiling standback v0.2.13
   Compiling unicase v2.6.0
   Compiling error-chain v0.12.4
   Compiling time v0.2.23
   Compiling cookie v0.14.3
   Compiling futures-task v0.3.8
   Compiling tracing-core v0.1.17
   Compiling thread_local v1.0.1
   Compiling indexmap v1.6.0
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling futures-channel v0.3.8
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling hashbrown v0.9.1
   Compiling walkdir v2.3.1
   Compiling http v0.2.1
   Compiling ring v0.16.16
   Compiling libsqlite3-sys v0.20.1
   Compiling synom v0.11.3
   Compiling textwrap v0.11.0
   Compiling itertools v0.9.0
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling hashlink v0.6.0
   Compiling syn v0.11.11
   Compiling http-body v0.3.1
   Compiling quote v1.0.7
   Compiling net2 v0.2.35
   Compiling iovec v0.1.4
   Compiling num_cpus v1.13.0
   Compiling signal-hook-registry v1.2.2
   Compiling time v0.1.44
   Compiling socket2 v0.3.17
   Compiling rand_os v0.1.3
   Compiling atty v0.2.14
   Compiling tracing v0.1.21
   Compiling want v0.3.0
   Compiling mio v0.7.6
   Compiling aho-corasick v0.7.15
   Compiling semver v0.9.0
   Compiling bincode v1.3.1
   Compiling mio v0.6.22
   Compiling rand_core v0.5.1
   Compiling pest_derive v1.0.8
   Compiling clap v2.33.3
   Compiling mime_guess v2.0.3
   Compiling regex v1.4.2
   Compiling rusqlite v0.24.1
   Compiling sct v0.6.0
   Compiling webpki v0.21.3
   Compiling mio-uds v0.6.8
   Compiling rand_chacha v0.2.2
   Compiling pin-project-internal v1.0.2
   Compiling futures-macro v0.3.8
   Compiling tokio-macros v0.2.6
   Compiling time-macros-impl v0.1.1
   Compiling gotham_derive v0.5.0
   Compiling chrono v0.4.19
   Compiling rustls v0.18.1
   Compiling rand v0.7.3
   Compiling pin-project v1.0.2
   Compiling tokio v0.2.23
   Compiling pin-project v0.4.27
   Compiling time-macros v0.1.1
   Compiling cargo_metadata v0.10.0
   Compiling uuid v0.8.1
   Compiling futures-util v0.3.8
   Compiling tempfile v3.1.0
   Compiling tracing-futures v0.2.4
   Compiling skeptic v0.13.5
   Compiling tokio-util v0.3.1
   Compiling tokio-rustls v0.14.1
   Compiling futures-executor v0.3.8
   Compiling borrow-bag v1.0.0
   Compiling h2 v0.2.7
   Compiling futures v0.3.8
   Compiling hyper v0.13.9
   Compiling gotham v0.5.0
   Compiling elexis-dictionary-service v0.1.0 (/home/jmccrae/projects/elexis/dictionary-service)
    Finished release [optimized] target(s) in 4m 33s
jmccrae@nacreous [10:10:45] [~/projects/elexis/dictionary-service] [master *]
-> % rustc --version
rustc 1.48.0 (7eac88abb 2020-11-16)
```

It does seem that I was committing the `Cargo.lock` file, so I have now removed this from the repo, perhaps this will help?

**Comment by kernc** [comment]
That did it. I thought Cargo.lock was repopulated on `cargo update`, but that didn't work for me previously. Confusing. :confused:

Thanks!
